### ISSUE TITLE
dcc - Update Daco2Ego for 25k / Legacy / DCC to support both v1 and v2 approved lists

### ISSUE THREAD

**Issue by akachru-github** [icgc-dcc/Daco2Ego#26]
- Permissions are required for this application to reach out to the DACO v2 system to retrieve the v2 approval file. 
  - We will need to get client creds from both Ego 2 (legacy) and Ego 4.x (because it is reaching out to DACO v2 website)
- Any updates to DACO2Ego (25k or ARGO) will require IT coordination to deploy.

**Comment by akachru-github** [comment]
- Will need @joneubank 's help to see what environments are available for testing this change.

**Comment by anncatton** [comment]
tested against a local dac-api / local ego v5 / local ego v2.3.2, and against argo-dev dac-api / argo dev ego / local ego v.2.3.2

**Comment by anncatton** [comment]
Tested by @blabadi and @anncatton in prod
