### ISSUE TITLE
[ICGC-DCC] Coordinate V1 Shutdown with IT

### ISSUE THREAD

**Issue by b-f-chan** [icgc-dcc/Daco2Ego#32]
Coordinate Daco V1 shutdown with IT as relates to Daco2Ego for ICGC-DCC

**Required by SoftEng To Do:**

- [x] Update ICGC-ARGO Daco2Ego app --> Remove all references to v1 files to prevent script from crashing.  Requires interaction with IT --> Changes must be merged and deployed in production **after** IT shuts down V1 (to be done in another ticket https://github.com/icgc-argo/Daco2Ego/issues/17)
- [x] Update ICGC25K DCC Daco2Ego app --> Remove all references to v1 files to prevent script from crashing.  Requires interaction with IT --> Changes must be merged and deployed in production **after** IT shuts down V1  
- [x] Email EGA (Aina, cc: Andrea Mero) --> Courtesy email to EGA to inform them they will receive only one list going forward
- [x] Email DACO Admin (Judith, Amber) --> Courtesy email to DACO admins to inform them V1 has been shut down (Melanie emailed Judith/Amber May 16, 2023 for final confirmation we can proceed with V1 shutdown)

**Not Required:**

- Archiving of v1 resources (confirmed with Melanie/Amber/Judith)

**Comment by anncatton** [comment]
Verified new version of Daco2Ego in production; confirmed with IT. V1 is retired as of 2023-05-30.
